### ISSUE TITLE
[BUG] Potion effects still show localized key names

### ISSUE THREAD

**Issue by LittleChest** [Darkhax-Minecraft/Level-Text-Fix#2]
### Minecraft Version

1.20.4

### Mod Version

10.0.2

### Mod Loader

Fabric

### What environment are you running the mod in?

Client

### Issue Description

![3e5b12508ce7e8a1f14f509903715a9c](https://github.com/Darkhax-Minecraft/Level-Text-Fix/assets/81231195/9bdc07e5-a187-440c-949f-7edbb48d4c3e)
Localized key names are still displayed when the potion effect is greater than or equal to ten levels

**Comment by Darkhax** [comment]
Hello, thanks for letting me know about this. The fixes included with this mod don't affect potions but it's something I can look into adding.

**Comment by Darkhax** [comment]
This should now be fixed in [10.0.3](https://www.curseforge.com/minecraft/mc-mods/level-text-fix/files/5164448). Please let me know how it goes.
