### ISSUE TITLE
[BUG] The number 200 is not displayed correctly

### ISSUE THREAD

**Issue by xleb-normal** [Darkhax-Minecraft/Level-Text-Fix#5]
### Minecraft Version

1.21.1

### Mod Version

LevelTextFix-fabric-1.21.1-21.1.1

### Mod Loader

Fabric

### What environment are you running the mod in?

All

### Issue Description

The number 200 is not displayed correctly 
![2024-10-09_15 32 03](https://github.com/user-attachments/assets/6a9d540e-7f24-4d3f-a86a-dc8884084e58)

**Comment by Darkhax** [comment]
Thank you for reporting this issue. The mod only supports up to 127 currently but it looks like the actual limit is 255. A fix should be available soon.
